name: 'equities_analytics_lakehouse'
version: '1.0.0'
config-version: 2

profile: 'equities_analytics_lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  equities_analytics_lakehouse:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +schema: marts
      dim_tickers:
        +materialized: table
      fct_daily_prices:
        +materialized: incremental
