version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_stock_data
        columns:
          - name: symbol
            tests: [not_null]
          - name: date
            tests: [not_null]
          - name: open
            tests: [not_null]
          - name: close
            tests: [not_null]
          - name: volume
            tests: [not_null]
          - name: extracted_at
            tests: [not_null]
